version: "3.8"

services:
  # Bank Simulator - 3rd party API Mock
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
        
  #PostgreSQL - data storage
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments-db
    ports:
      - "5432:5432"

  # Jaeger - Observability Exporter
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "13133:13133"
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
  
  #Payment Gateway API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
      - bank_simulator
      - jaeger
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments-db
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8081:8080"
      - "443:443"